# model configuration
batch_size: 50
eval_batch_size: 50
lr: 1.0
embedding_size: 300
num_classes: 2
keep_prob: 0.6
clipped_norm: 3
optimizer: adadelta
conv_filters:
    - size: 3
      channels: 100
    - size: 4
      channels: 100
    - size: 5
      channels: 100
max_epochs: 20
shuffle: True
cnn_mode: nonstatic

## Iterative Distillation Configuration
iterative: True
l1_schedule: logicnn
l1_val: 1.0

# ELMo word representations
elmo: False