# model configuration
batch_size: 50
eval_batch_size: 50
lr: 1.0
embedding_size: 300
num_classes: 2
keep_prob: 0.6
clipped_norm: 3
optimizer: adadelta
conv_filters:
    - size: 3
      channels: 100
    - size: 4
      channels: 100
    - size: 5
      channels: 100
max_epochs: 20
eval_frequency: 100000000
mask: False
shuffle: True
cnn_mode: nonstatic
# iterative configuration
iterative: True
l1_schedule: logicnn
algorithm: logicnn
data: batch
rescale: True
iterative_epochs: 5
use_log_prob: True
perceptron_shuffle: True
# perceptron SGD config
perceptron_batch_size: 16
perceptron_lr: 0.5
# perceptron weighted config
granularity: 0.001
